defaults: &defaults
  uri: <%= uri = URI.parse(ENV['REDIS_PROVIDER_URL'] || "redis://localhost:6379") %>
  port: <%= uri.port %>
  password: <%= uri.password %>
  db: <%= GlobalSetting.redis_db %>

development:
  <<: *defaults

profile:
  <<: *defaults

test:
  <<: *defaults
  db: 1

staging:
  <<: *defaults

production:
  <<: *defaults
